"""The backfill must know about every column, on both sides.

Why this test exists
--------------------
scripts/backfill_child_tables.py copies rows from SQLite into the Postgres tables
from migration 012. It lists its columns explicitly. If someone adds a column to
`drafts` and not to the script, the backfill still "succeeds" — it just silently
drops that column's contents for every row it copies, and nobody finds out until
a lawyer notices a field is blank.

So three column sets have to agree, and this test is what makes them agree:

    the storage module's own SELECT list   (what SQLite actually holds)
    the script's Spec.cols                 (what gets copied)
    migration 012's CREATE TABLE           (what Postgres accepts)

The one deliberate asymmetry is documents.search_tsv: GENERATED ALWAYS, so
Postgres computes it and a payload containing it is rejected.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from headnote.entitlements import _supabase
from scripts.backfill_child_tables import (
    CONSULTATIONS, DOCUMENTS, DRAFTS, SPECS, prepare, write_rows,
)

ROOT = Path(__file__).resolve().parent.parent
MIGRATION = ROOT / "migrations" / "012_child_tables.sql"

# Computed by Postgres from title + full_text, so it is never sent.
_GENERATED = {"documents": {"search_tsv"}}


def _cols_from_tuple_literal(source: str, const: str) -> set[str]:
    """Pull the column names out of a `_COLS = ("a, b, " "c")` style constant.

    Read from source rather than imported so this test costs nothing at import
    time — headnote.documents.storage pulls in numpy and the embedding model.
    """
    m = re.search(rf"^{const}\s*=\s*\((.*?)\)\s*$", source, re.S | re.M)
    assert m, f"could not find {const} in the storage module"
    joined = " ".join(re.findall(r'"([^"]*)"', m.group(1)))
    return {c.strip() for c in joined.split(",") if c.strip()}


def _migration_cols(table: str) -> set[str]:
    sql = MIGRATION.read_text()
    m = re.search(rf"create table if not exists public\.{table}\s*\((.*?)\n\);",
                  sql, re.S | re.I)
    assert m, f"no CREATE TABLE for public.{table} in {MIGRATION.name}"
    cols = set()
    for line in m.group(1).splitlines():
        line = line.split("--")[0].strip()
        if not line:
            continue
        name = line.split()[0].strip(",")
        if name.lower() not in {"primary", "unique", "constraint", "foreign", "check"}:
            cols.add(name)
    # ALTER TABLE ... ADD COLUMN against the same table counts too.
    for name in re.findall(
            rf"alter table public\.{table}\s+add column if not exists (\w+)", sql, re.I):
        cols.add(name)
    return cols


STORAGE = {
    "drafts": ("headnote/drafter/storage.py", "_SELECT_COLS"),
    "consultations": ("headnote/consultations/storage.py", "_COLS"),
    "documents": ("headnote/documents/storage.py", "_COLS"),
}


@pytest.mark.parametrize("spec", [DRAFTS, CONSULTATIONS, DOCUMENTS],
                         ids=lambda s: s.name)
def test_script_matches_the_sqlite_select_list(spec):
    """Every column the app reads out of SQLite is a column the backfill copies."""
    path, const = STORAGE[spec.name]
    sqlite_cols = _cols_from_tuple_literal((ROOT / path).read_text(), const)
    assert sqlite_cols == set(spec.cols), (
        f"{spec.name}: the backfill and {path} disagree. "
        f"only in SQLite: {sorted(sqlite_cols - set(spec.cols))}; "
        f"only in the script: {sorted(set(spec.cols) - sqlite_cols)}"
    )


@pytest.mark.parametrize("spec", [DRAFTS, CONSULTATIONS, DOCUMENTS],
                         ids=lambda s: s.name)
def test_script_matches_the_migration(spec):
    """Nothing is copied that Postgres has no column for, and nothing storable
    is left behind."""
    pg_cols = _migration_cols(spec.name) - _GENERATED.get(spec.name, set())
    assert set(spec.cols) == pg_cols, (
        f"{spec.name}: the backfill and migration 012 disagree. "
        f"only in Postgres: {sorted(pg_cols - set(spec.cols))}; "
        f"only in the script: {sorted(set(spec.cols) - pg_cols)}"
    )


def test_generated_columns_are_never_sent():
    """search_tsv is GENERATED ALWAYS — including it makes Postgres reject the
    whole insert, which would fail the backfill for every document."""
    for table, generated in _GENERATED.items():
        assert not (generated & set(SPECS[table].cols)), (
            f"{table}: {generated & set(SPECS[table].cols)} is generated by "
            "Postgres and must not be in the payload")


def test_json_and_bool_columns_are_declared():
    """The type mismatches SQLite→Postgres are the ones that need converting:
    JSON stored as TEXT, and booleans stored as 0/1."""
    assert DRAFTS.json_cols == ("answers_json",)
    assert CONSULTATIONS.json_cols == ("report_json",)
    assert DOCUMENTS.json_cols == ("metadata_json",)
    assert CONSULTATIONS.bool_cols == ("consent",)


def test_id_is_copied_so_the_backfill_is_idempotent():
    """Ids are app-minted uuid4 hex, and that is the only reason a re-run can tell
    an already-copied row from a new one. Letting Postgres mint ids would make
    every run duplicate every row."""
    for spec in SPECS.values():
        assert "id" in spec.cols


# ------------------------------------------------- SQLite → Postgres transform
#
# Each of these is a type or constraint mismatch that would otherwise cost the
# row: Postgres rejects the payload, the row never arrives, and it is gone from
# the app the moment the flag goes on.

CID = "22222222-2222-4222-8222-222222222222"


def _prep(row, spec=DRAFTS, cases=frozenset({CID})):
    return prepare(row, spec, known_cases=set(cases))


def test_json_text_becomes_a_real_object():
    """answers_json is TEXT in SQLite and jsonb in Postgres. Sending the string
    would store a JSON *string*, and every read would come back unparseable."""
    got, why = _prep({"id": "a", "story_id": "s", "answers_json": '{"amount": "5000"}'})
    assert why == ""
    assert got.payload["answers_json"] == {"amount": "5000"}


def test_unparseable_json_keeps_the_row():
    """A corrupt metadata blob is not worth losing the draft over — but it is
    worth counting, so the run reports it."""
    got, why = _prep({"id": "a", "story_id": "s", "answers_json": "{not json"})
    assert why == ""
    assert got.payload["answers_json"] == {}
    assert got.repaired_json == ("answers_json",)


def test_sqlite_integer_consent_becomes_a_postgres_boolean():
    got, why = _prep({"id": "a", "consent": 1}, CONSULTATIONS)
    assert why == "" and got.payload["consent"] is True
    got, _ = _prep({"id": "a", "consent": 0}, CONSULTATIONS)
    assert got.payload["consent"] is False


def test_a_non_uuid_user_id_is_skipped_not_nulled():
    """user_id is `uuid references auth.users`. 'u_demo' is a local-dev id, never
    a real advocate's row — and nulling it would file the row under the anonymous
    listing, which is worse than not copying it."""
    got, why = _prep({"id": "a", "story_id": "s", "user_id": "u_demo"})
    assert got is None and "not a uuid" in why


def test_a_genuinely_anonymous_row_is_copied():
    """NULL user_id is legal in both schemas."""
    got, why = _prep({"id": "a", "story_id": "s", "user_id": None})
    assert why == "" and got.payload["user_id"] is None


def test_a_stale_case_link_is_cleared_and_the_row_survives():
    """case_id is a FK. Pointing at a matter Postgres doesn't have would make the
    insert fail and cost the whole draft — the link is worth less than the draft."""
    got, why = _prep({"id": "a", "story_id": "s", "case_id": "33333333-3333-4333-8333-333333333333"})
    assert why == ""
    assert got.payload["case_id"] is None
    assert got.unlinked_case is True


def test_a_live_case_link_is_preserved():
    got, why = _prep({"id": "a", "story_id": "s", "case_id": CID})
    assert why == "" and got.payload["case_id"] == CID and not got.unlinked_case


def test_a_missing_timestamp_is_omitted_so_the_default_applies():
    """created_at is NOT NULL DEFAULT now(). Sending null violates the constraint;
    omitting the key lets Postgres fill it."""
    got, _ = _prep({"id": "a", "story_id": "s", "created_at": "", "updated_at": None})
    assert "created_at" not in got.payload and "updated_at" not in got.payload


def test_a_present_timestamp_is_carried_across_verbatim():
    """The lawyer's own dates, not the migration's. An updated_at rewritten to now()
    would reorder every list view — newest-first would become migration order."""
    got, _ = _prep({"id": "a", "story_id": "s", "updated_at": "2026-03-04T05:06:07+00:00"})
    assert got.payload["updated_at"] == "2026-03-04T05:06:07+00:00"


def test_not_null_columns_without_a_default_are_coerced():
    """documents.title is NOT NULL. An empty string satisfies it; inventing a
    title would put words in the lawyer's file."""
    got, why = _prep({"id": "a", "title": None, "full_text": None,
                      "page_count": None}, DOCUMENTS)
    assert why == ""
    assert got.payload["title"] == "" and got.payload["full_text"] == ""
    assert got.payload["page_count"] == 1


def test_a_column_absent_from_sqlite_is_omitted_entirely():
    """Older databases predate the guarded `ALTER TABLE ... ADD COLUMN case_id`,
    and a read-only connection cannot add it. Omitting the key lets the Postgres
    default apply; sending null would fight a NOT NULL constraint."""
    got, why = _prep({"id": "a", "story_id": "s"})
    assert why == ""
    assert "case_id" not in got.payload
    assert "exported_at" not in got.payload


def test_a_row_missing_a_truly_required_column_is_reported():
    """drafts.story_id is NOT NULL with no default — Postgres would reject it, so
    say which row and why instead of failing the batch."""
    got, why = _prep({"id": "a", "story_id": None})
    assert got is None and "story_id" in why


def test_a_row_with_no_id_is_reported():
    got, why = _prep({"story_id": "s"})
    assert got is None and why == "no id"


def test_a_bad_row_costs_one_row_not_the_batch():
    """A batch is one statement, so one rejected row fails all fifty. The
    row-by-row retry is what stops a single bad row blocking the migration."""
    calls = {"batch": 0, "single": 0}

    def fake_upsert(table, payload, *, on_conflict=None, timeout=None):
        if isinstance(payload, list):
            calls["batch"] += 1
            raise _supabase.SupabaseError("HTTP 400: one of these is bad", status=400)
        calls["single"] += 1
        if payload["id"] == "bad":
            raise _supabase.SupabaseError("HTTP 400: nope", status=400)
        return [payload]

    import scripts.backfill_child_tables as bf
    original = bf._supabase.upsert_or_raise
    bf._supabase.upsert_or_raise = fake_upsert
    try:
        written, errors = write_rows("drafts", [{"id": "ok1"}, {"id": "bad"},
                                                {"id": "ok2"}], overwrite=False)
    finally:
        bf._supabase.upsert_or_raise = original

    assert written == 2, "the good rows must still land"
    assert len(errors) == 1 and "bad" in errors[0]
    assert calls["batch"] == 1 and calls["single"] == 3
