-- migrations/008_saved_caselaw.sql
--
-- Per-user "saved case-law" library — precedents a lawyer found useful in
-- research and wants to keep for future matters.
--
-- Why snapshot the whole case (case_json) instead of just an id?
-- The valuable part of a research hit — the stinger sentence, HELD line,
-- court quote and 4-dimension match analysis — is generated by the LLM
-- *for that specific situation*. It is NOT a static property of the case.
-- If we stored only case_id and re-fetched later we'd lose exactly what made
-- the lawyer keep it (and re-generating would cost an LLM call against a
-- different query). So we store the full card object as JSONB; the frontend
-- re-renders it identically with zero LLM cost. source_query records the
-- situation it came from so the lawyer remembers *why* they saved it.
--
-- Used by:
--   POST   /api/saved-caselaw            (headnote/api/saved_caselaw.py — save / upsert)
--   GET    /api/saved-caselaw            (headnote/api/saved_caselaw.py — list, newest first)
--   PATCH  /api/saved-caselaw/{case_id}  (headnote/api/saved_caselaw.py — edit the note)
--   DELETE /api/saved-caselaw/{case_id}  (headnote/api/saved_caselaw.py — unsave)
--
-- Idempotent — safe to run multiple times. Run in: Supabase dashboard -> SQL Editor -> paste -> Run.

CREATE TABLE IF NOT EXISTS public.saved_caselaw (
  id              BIGSERIAL PRIMARY KEY,
  -- Cascade: a saved library has no meaning without its owner.
  user_id         UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  -- Stable cross-source identifier: 'ik:529907' (Indian Kanoon) or
  -- 'BHASK-1999-SC' (curated). One save per (user, case) — re-saving updates.
  case_id         TEXT NOT NULL,
  -- Denormalised display columns so the list view renders without parsing
  -- the JSON blob. Mirror of fields inside case_json.
  title           TEXT,
  citation        TEXT,
  court           TEXT,
  year            TEXT,           -- kept as text; some sources give '' / ranges
  source          TEXT,           -- 'curated' | 'ik' | 'hf-semantic' | 'hf-keyword'
  -- The full normalised card object, re-rendered as-is in the Saved view.
  case_json       JSONB NOT NULL,
  -- The research situation that produced this hit (so they recall the why).
  source_query    TEXT,
  -- The lawyer's own note — e.g. "use for the bail argument, para 14".
  note            TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- One row per case per user; enables upsert via on_conflict=user_id,case_id.
  CONSTRAINT uq_saved_caselaw_user_case UNIQUE (user_id, case_id)
);

-- The library is read newest-first, scoped to one user.
CREATE INDEX IF NOT EXISTS idx_saved_caselaw_user_created
  ON public.saved_caselaw (user_id, created_at DESC);

-- Backend uses the service-role key (bypasses RLS). Enable RLS with no policy
-- to hard-deny the anon/auth roles in case the anon key ever touches this
-- table by mistake (matches the convention in 003_assist_requests.sql).
ALTER TABLE public.saved_caselaw ENABLE ROW LEVEL SECURITY;
