"""LLM prompt templates, Claude client wrapper, and model router."""

from .prompts import (
    build_situation_system_prompt,
    SITUATION_USER_TEMPLATE,
    SITUATION_USER_TEMPLATE_V2,
    build_situation_user_v2,
    HEADNOTE_SYSTEM_PROMPT,
    HEADNOTE_USER_TEMPLATE,
    HEADNOTE_VERIFY_SYSTEM_PROMPT,
    HEADNOTE_VERIFY_USER_TEMPLATE,
    build_digest_system_prompt,
    DIGEST_USER_TEMPLATE,
)
from .client import (
    get_client,
    call_claude_cached,
    estimate_cost_usd,
    parse_json_response,
    build_meta,
)
from .router import (
    TaskType,
    RouteResult,
    route_call,
    build_router_meta,
    calculate_cost_paise,
    parse_and_strip_confidence,
    CONFIDENCE_PROMPT_SUFFIX,
    CONFIDENCE_RETRY_THRESHOLD,
    HAIKU_MODEL,
    SONNET_MODEL,
    OPUS_MODEL,
)

__all__ = [
    "build_situation_system_prompt",
    "SITUATION_USER_TEMPLATE",
    "SITUATION_USER_TEMPLATE_V2",
    "build_situation_user_v2",
    "HEADNOTE_SYSTEM_PROMPT",
    "HEADNOTE_USER_TEMPLATE",
    "HEADNOTE_VERIFY_SYSTEM_PROMPT",
    "HEADNOTE_VERIFY_USER_TEMPLATE",
    "build_digest_system_prompt",
    "DIGEST_USER_TEMPLATE",
    "get_client",
    "call_claude_cached",
    "estimate_cost_usd",
    "parse_json_response",
    "build_meta",
    "TaskType",
    "RouteResult",
    "route_call",
    "build_router_meta",
    "calculate_cost_paise",
    "parse_and_strip_confidence",
    "CONFIDENCE_PROMPT_SUFFIX",
    "CONFIDENCE_RETRY_THRESHOLD",
    "HAIKU_MODEL",
    "SONNET_MODEL",
    "OPUS_MODEL",
]
